### ISSUE TITLE
Pretrained model request

### ISSUE THREAD

**Issue by ChenDarYen** [krushi1992/MOA-transformer#3]
Hi, your work is amazing! May I ask if its possible to get the pretrained model of 224 tiny, small and base MOA-Transformer.
My email is dc00875@surrey.ac.uk. Thank you very much!

**Comment by krushi1992** [comment]
Sent

**Comment by krushi1992** [comment]
Could you please double-check the email Id you gave me?

**Comment by krushi1992** [comment]
> Hi, your work is amazing! May I ask if its possible to get the pretrained model of 224 tiny, small and base MOA-Transformer. My email is [dc00875@surrey.ac.uk](mailto:dc00875@surrey.ac.uk). Thank you very much!

Could you please double-check the email Id you gave me?

**Comment by ChenDarYen** [comment]
Oh I type a wrong id, sorry about that. The correct id is dc00872@surrey.ac.uk. Thanks you!!

**Comment by ChenDarYen** [comment]
> > Hi, your work is amazing! May I ask if its possible to get the pretrained model of 224 tiny, small and base MOA-Transformer. My email is [dc00875@surrey.ac.uk](mailto:dc00875@surrey.ac.uk). Thank you very much!
> 
> Could you please double-check the email Id you gave me?

Oh I type a wrong id, sorry about that. The correct email id is dc00872@surrey.ac.uk. Thanks you!!

**Comment by krushi1992** [comment]
Sent.
